/*
This file is automatically generated
barbecue
Header
*/

#ifndef barbecue__H
#define barbecue__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell barbecue(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo barbecue__Info;

ESD_FUNCTION(barbecue_0, Type = Ft_Esd_BitmapCell, DisplayName = "barbecue", Include = "barbecue.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define barbecue_0() ((Ft_Esd_BitmapCell){ .Info = &barbecue__Info, .Cell = 0 })

#endif /* barbecue__H */

/* end of file */
