/*
This file is automatically generated
diveevo
Header
*/

#ifndef diveevo__H
#define diveevo__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell diveevo(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo diveevo__Info;

ESD_FUNCTION(diveevo_0, Type = Ft_Esd_BitmapCell, DisplayName = "diveevo", Include = "diveevo.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define diveevo_0() ((Ft_Esd_BitmapCell){ .Info = &diveevo__Info, .Cell = 0 })

#endif /* diveevo__H */

/* end of file */
