/*
This file is automatically generated
diveevo
C Source
*/

#include "diveevo.h"

#include "Ft_Gpu.h"

Ft_Esd_BitmapInfo diveevo__Info = {
	ESD_BITMAP_DEFAULTS,
	.Width = 320,
	.Height = 240,
	.Format = RGB565,
	.Stride = 640,
	.Size = 153600,
	.File = "diveevo.raw",
	.Cells = 1,
	.Compressed = 0,
	.Persistent = 0,
	.Type = ESD_RESOURCE_FILE,
};

Ft_Esd_BitmapCell diveevo(ft_uint16_t cell)
{
	return (Ft_Esd_BitmapCell){ 
		.Info = &diveevo__Info, 
		.Cell = cell 
	};
}


/* end of file */
