/*
This file is automatically generated
fire
Header
*/

#ifndef fire__H
#define fire__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell fire(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo fire__Info;

ESD_FUNCTION(fire_0, Type = Ft_Esd_BitmapCell, DisplayName = "fire", Include = "fire.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define fire_0() ((Ft_Esd_BitmapCell){ .Info = &fire__Info, .Cell = 0 })

#endif /* fire__H */

/* end of file */
