/*
This file is automatically generated
DO NOT MODIFY BY HAND
FirstPage
C Source
*/

#include "FirstPage.h"

#include "Esd_Context.h"
ESD_CORE_EXPORT void Esd_Noop(void *context);

static uint8_t FirstPage_ESD_Label_2_Font__Property(void *context) { return 30; }
static const char * FirstPage_ESD_Label_2_Text__Property(void *context) { return "CoverFlow Animation"; }
static Esd_BitmapCell FirstPage_Usr_Widget_ImageArray__Property_Array[9];
static const Esd_BitmapCell* FirstPage_Usr_Widget_ImageArray__Property(void *context, size_t *size) { *size = 9; return FirstPage_Usr_Widget_ImageArray__Property_Array; }
static uint8_t FirstPage_ESD_Label_Font__Property(void *context) { return 31; }
static const char * FirstPage_ESD_Label_Text__Property(void *context) { return "ESD"; }

static Ft_Esd_WidgetSlots s_FirstPage__Slots = {
	(void(*)(void *))Ft_Esd_Widget_Initialize,
	(void(*)(void *))Ft_Esd_Widget_Start,
	(void(*)(void *))Ft_Esd_Widget_Enable,
	(void(*)(void *))Ft_Esd_Widget_Update,
	(void(*)(void *))Ft_Esd_Widget_Render,
	(void(*)(void *))Ft_Esd_Widget_Idle,
	(void(*)(void *))Ft_Esd_Widget_Disable,
	(void(*)(void *))FirstPage_End,
};


void FirstPage__Fixed_Position__Initializer(FirstPage *context)
{
	Ft_Esd_Layout_Fixed *object = (Ft_Esd_Layout_Fixed *)&context->Fixed_Position;
	Ft_Esd_Layout_Fixed__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 50;
	object->Widget.LocalHeight = 50;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)context);
}

void FirstPage__ESD_Scrolling_Text__Initializer(FirstPage *context)
{
	Ft_Esd_ScrollingText *object = (Ft_Esd_ScrollingText *)&context->ESD_Scrolling_Text;
	Ft_Esd_ScrollingText__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 208;
	object->Widget.LocalY = 419;
	object->Widget.LocalWidth = 320;
	object->Widget.LocalHeight = 37;
	object->Font = 30L;
	object->Position = RIGHT_TO_LEFT;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__ESD_Label_2__Initializer(FirstPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label_2;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 256;
	object->Widget.LocalY = 13;
	object->Widget.LocalWidth = 296;
	object->Widget.LocalHeight = 50;
	object->Font = FirstPage_ESD_Label_2_Font__Property;
	object->Text = FirstPage_ESD_Label_2_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Usr_Widget__Initializer(FirstPage *context)
{
	Usr_Widget *object = (Usr_Widget *)&context->Usr_Widget;
	Usr_Widget__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 50;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 400;
	FirstPage_Usr_Widget_ImageArray__Property_Array[0] = barbecue_0();
	FirstPage_Usr_Widget_ImageArray__Property_Array[1] = chess_0();
	FirstPage_Usr_Widget_ImageArray__Property_Array[2] = diveevo_0();
	FirstPage_Usr_Widget_ImageArray__Property_Array[3] = fire_0();
	FirstPage_Usr_Widget_ImageArray__Property_Array[4] = keyboard_0();
	FirstPage_Usr_Widget_ImageArray__Property_Array[5] = locomotive_0();
	FirstPage_Usr_Widget_ImageArray__Property_Array[6] = person_0();
	FirstPage_Usr_Widget_ImageArray__Property_Array[7] = rose_0();
	FirstPage_Usr_Widget_ImageArray__Property_Array[8] = seagull_0();
	object->ImageArray = FirstPage_Usr_Widget_ImageArray__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__ESD_Label__Initializer(FirstPage *context)
{
	Ft_Esd_Label *object = (Ft_Esd_Label *)&context->ESD_Label;
	Ft_Esd_Label__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 4;
	object->Widget.LocalY = 1;
	object->Widget.LocalWidth = 120;
	object->Widget.LocalHeight = 36;
	object->Font = FirstPage_ESD_Label_Font__Property;
	object->Text = FirstPage_ESD_Label_Text__Property;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__ESD_Multi_Gradient__Rounded___Initializer(FirstPage *context)
{
	Ft_Esd_MultiGradientRounded *object = (Ft_Esd_MultiGradientRounded *)&context->ESD_Multi_Gradient__Rounded_;
	Ft_Esd_MultiGradientRounded__Initializer(object);
	object->Owner = (void *)context;
	object->Widget.Active = 1;
	object->Widget.LocalX = 0;
	object->Widget.LocalY = 0;
	object->Widget.LocalWidth = 800;
	object->Widget.LocalHeight = 480;
	object->TopLeft = 0x19f7UL;
	object->TopRight = 0x19f7UL;
	object->BottomLeft = 0x218UL;
	object->BottomRight = 0x218UL;
	Ft_Esd_Widget_InsertBottom((Ft_Esd_Widget *)object, (Ft_Esd_Widget *)&context->Fixed_Position);
}

void FirstPage__Initializer(FirstPage *context)
{
	Ft_Esd_Widget__Initializer((Ft_Esd_Widget *)context);
	context->Widget.ClassId = FirstPage_CLASSID;
	context->Widget.Slots = &s_FirstPage__Slots;
	context->Widget.LocalX = 0;
	context->Widget.LocalY = 0;
	context->Widget.LocalWidth = 400;
	context->Widget.LocalHeight = 300;
	FirstPage__Fixed_Position__Initializer(context);
	FirstPage__ESD_Scrolling_Text__Initializer(context);
	FirstPage__ESD_Label_2__Initializer(context);
	FirstPage__Usr_Widget__Initializer(context);
	FirstPage__ESD_Label__Initializer(context);
	FirstPage__ESD_Multi_Gradient__Rounded___Initializer(context);
}

void FirstPage_End(FirstPage *context)
{
	void *owner = context->Owner;
	Ft_Esd_Widget_End((Ft_Esd_Widget *)context);
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Fixed_Position); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Scrolling_Text); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label_2); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->Usr_Widget); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Label); 
	Ft_Esd_Widget_Detach((Ft_Esd_Widget *)&context->ESD_Multi_Gradient__Rounded_); 
}


/* end of file */
