/*
This file is automatically generated
keyboard
Header
*/

#ifndef keyboard__H
#define keyboard__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell keyboard(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo keyboard__Info;

ESD_FUNCTION(keyboard_0, Type = Ft_Esd_BitmapCell, DisplayName = "keyboard", Include = "keyboard.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define keyboard_0() ((Ft_Esd_BitmapCell){ .Info = &keyboard__Info, .Cell = 0 })

#endif /* keyboard__H */

/* end of file */
