/*
This file is automatically generated
locomotive
Header
*/

#ifndef locomotive__H
#define locomotive__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell locomotive(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo locomotive__Info;

ESD_FUNCTION(locomotive_0, Type = Ft_Esd_BitmapCell, DisplayName = "locomotive", Include = "locomotive.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define locomotive_0() ((Ft_Esd_BitmapCell){ .Info = &locomotive__Info, .Cell = 0 })

#endif /* locomotive__H */

/* end of file */
