/*
This file is automatically generated
rose
Header
*/

#ifndef rose__H
#define rose__H

#ifndef ESD_FUNCTION
#define ESD_FUNCTION(name, ...)
#endif

#include "Ft_DataTypes.h"
#include "Ft_Esd_BitmapInfo.h"

Ft_Esd_BitmapCell rose(ft_uint16_t cell);

extern Ft_Esd_BitmapInfo rose__Info;

ESD_FUNCTION(rose_0, Type = Ft_Esd_BitmapCell, DisplayName = "rose", Include = "rose.h", Category = _GroupUserResources, Icon = ":/icons/image.png", Macro)
#define rose_0() ((Ft_Esd_BitmapCell){ .Info = &rose__Info, .Cell = 0 })

#endif /* rose__H */

/* end of file */
